CREATE TABLE flowersData (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(40) NOT NULL,
  price VARCHAR(15) NOT NULL
);

INSERT INTO flowersData
  (name, price)
VALUES
  ('Boho Vibes', '35'),
  ('Herbstsonne', '45'),
  ('Kreative Überraschung', '55'),
  ('Purple Dream', '40'),
  ('Red Naomi Rosen', '35'),
  ('Bemy Baby', '40');




  const flowersdata = [
  {
    name: 'Boho Vibes',
    price: 35,
  },
  {
    name: 'Herbstsonne',
    price: 45,
  },
  {
    name: 'Kreative Überraschung',
    price: 50,
  },
  {
    name: 'Purple Dream',
    price: 35,
  },
  {
    name: 'Red Naomi Rosen',
    price: 25,
  },
  {
    name: 'Bemy Baby',
    price: 30,
  },
  {
    name: 'Zarte Blümchen',
    price: 35,
  },
  {
    name: 'Sonnige Freude',
    price: 25,
  },
  {
    name: 'Errötender Herbst',
    price: 40,
  },
];